CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128),
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS CONTACT (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PHONE_NUMBER VARCHAR(12),
    COMPANY_NAME VARCHAR(255),
    CONTACT_NAME VARCHAR(255),
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS TASK (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    DESCRIPTION VARCHAR(1000),
    "TIME" TIMESTAMP,
    CAR_ID INT,
    PRIMARY KEY (ID)
    );

CREATE TABLE IF NOT EXISTS TASK_EMPLOYEE (
    TASK_ID INTEGER NOT NULL,
    EMPLOYEE_ID INTEGER NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES employee(ID),
    PRIMARY KEY (TASK_ID, EMPLOYEE_ID)
    );

CREATE TABLE IF NOT EXISTS CONTACT_TASK (
    CONTACT_ID INTEGER NOT NULL,
    TASK_ID INTEGER NOT NULL,
    FOREIGN KEY (TASK_ID) REFERENCES TASK(ID),
    FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID),
    PRIMARY KEY (CONTACT_ID, TASK_ID)
    );